// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozjurrttdvwhanaofnod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96anVycnR0ZHZ3aGFuYW9mbm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNjEwNjcsImV4cCI6MjA5MDYzNzA2N30.E2yfzoPvIVbE4Ty-_oODS5MCD46rZVAHRXzdEE6QhbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});